# Generated by Django 5.2.7 on 2025-11-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_driveravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveravailability',
            options={'verbose_name': 'Driver Availability', 'verbose_name_plural': 'Driver Availabilities'},
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
    ]
