# Generated by Django 5.2.7 on 2025-11-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_driveravailability_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverAvailability',
        ),
    ]
