# Generated by Django 5.2.7 on 2025-11-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_ridingevent_stripe_payment_intent_id_stripepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridingevent',
            options={'ordering': ['-created_at']},
        ),
    ]
