# Generated by Django 5.2.7 on 2025-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='car_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='driving_license_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driving_licenses/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver')], default='user', max_length=10),
        ),
    ]
