# Generated by Django 5.2.7 on 2025-10-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_car_name_customuser_car_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
