# Generated by Django 5.2.7 on 2025-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_otp_code_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
