# Generated by Django 5.2.7 on 2025-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_last_password_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], max_length=50, null=True),
        ),
    ]
