# Generated by Django 5.2.7 on 2025-11-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike')], max_length=50, null=True),
        ),
    ]
