# Generated by Django 5.2.7 on 2025-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_transport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='transport_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='driver_is_available',
            field=models.BooleanField(default=True),
        ),
    ]
